# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

MM=/usr/bin/gcc
MXX=/usr/bin/gcc
CC=/usr/bin/gcc
CXX=/usr/bin/gcc
AS=/usr/bin/gcc

LD=/usr/bin/g++
SH=/usr/bin/g++
AR=/usr/bin/ar

iclient_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -Iinclude -I/usr/local/curl/include -Wreturn-type -Wsign-compare -Wunused -Wswitch -Wno-deprecated-declarations -DNDEBUG
iclient_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -Iinclude -I/usr/local/curl/include -Wreturn-type -Wsign-compare -Wunused -Wswitch -Wno-deprecated-declarations -DNDEBUG
iclient_ARFLAGS=-cr
example.out_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -Iinclude -I/usr/local/curl/include -Wreturn-type -Wsign-compare -Wunused -Wswitch -Wno-deprecated-declarations -DNDEBUG
example.out_CXXFLAGS=-m64 -fvisibility=hidden -fvisibility-inlines-hidden -O3 -std=c++11 -Iinclude -I/usr/local/curl/include -Wreturn-type -Wsign-compare -Wunused -Wswitch -Wno-deprecated-declarations -DNDEBUG
example.out_LDFLAGS=-m64 -L. -L/usr/local/curl/lib -Llib/linux -s -liclient -lcurl -lpthread -ldl

default:  iclient example.out

all:  iclient example.out

.PHONY: default all  iclient example.out

iclient: lib/linux/libiclient.a
lib/linux/libiclient.a: build/.objs/iclient/linux/x86_64/release/src/request.cpp.o build/.objs/iclient/linux/x86_64/release/src/response.cpp.o build/.objs/iclient/linux/x86_64/release/src/executor.cpp.o build/.objs/iclient/linux/x86_64/release/src/http.cpp.o build/.objs/iclient/linux/x86_64/release/src/url.cpp.o build/.objs/iclient/linux/x86_64/release/src/util.cpp.o
	@echo linking.release libiclient.a
	@mkdir -p lib/linux
	@$(AR) $(iclient_ARFLAGS) lib/linux/libiclient.a build/.objs/iclient/linux/x86_64/release/src/request.cpp.o build/.objs/iclient/linux/x86_64/release/src/response.cpp.o build/.objs/iclient/linux/x86_64/release/src/executor.cpp.o build/.objs/iclient/linux/x86_64/release/src/http.cpp.o build/.objs/iclient/linux/x86_64/release/src/url.cpp.o build/.objs/iclient/linux/x86_64/release/src/util.cpp.o > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/request.cpp.o: src/request.cpp
	@echo compiling.release src/request.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/request.cpp.o src/request.cpp > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/response.cpp.o: src/response.cpp
	@echo compiling.release src/response.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/response.cpp.o src/response.cpp > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/executor.cpp.o: src/executor.cpp
	@echo compiling.release src/executor.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/executor.cpp.o src/executor.cpp > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/http.cpp.o: src/http.cpp
	@echo compiling.release src/http.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/http.cpp.o src/http.cpp > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/url.cpp.o: src/url.cpp
	@echo compiling.release src/url.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/url.cpp.o src/url.cpp > build/.build.log 2>&1

build/.objs/iclient/linux/x86_64/release/src/util.cpp.o: src/util.cpp
	@echo compiling.release src/util.cpp
	@mkdir -p build/.objs/iclient/linux/x86_64/release/src
	@$(CXX) -c $(iclient_CXXFLAGS) -o build/.objs/iclient/linux/x86_64/release/src/util.cpp.o src/util.cpp > build/.build.log 2>&1

example.out: bin/example.out
bin/example.out: lib/linux/libiclient.a build/.objs/example.out/linux/x86_64/release/example/test_url.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_range.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_post.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_speed_limit.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download.cpp.o build/.objs/example.out/linux/x86_64/release/example/main.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_resume.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_put.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_get.cpp.o
	@echo linking.release example.out
	@mkdir -p bin
	@$(LD) -o bin/example.out build/.objs/example.out/linux/x86_64/release/example/test_url.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_range.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_post.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_speed_limit.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download.cpp.o build/.objs/example.out/linux/x86_64/release/example/main.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_download_resume.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_put.cpp.o build/.objs/example.out/linux/x86_64/release/example/test_http_get.cpp.o $(example.out_LDFLAGS) > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_url.cpp.o: example/test_url.cpp
	@echo compiling.release example/test_url.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_url.cpp.o example/test_url.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_download_range.cpp.o: example/test_download_range.cpp
	@echo compiling.release example/test_download_range.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_download_range.cpp.o example/test_download_range.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_http_post.cpp.o: example/test_http_post.cpp
	@echo compiling.release example/test_http_post.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_http_post.cpp.o example/test_http_post.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_download_speed_limit.cpp.o: example/test_download_speed_limit.cpp
	@echo compiling.release example/test_download_speed_limit.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_download_speed_limit.cpp.o example/test_download_speed_limit.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_download.cpp.o: example/test_download.cpp
	@echo compiling.release example/test_download.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_download.cpp.o example/test_download.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/main.cpp.o: example/main.cpp
	@echo compiling.release example/main.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/main.cpp.o example/main.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_download_resume.cpp.o: example/test_download_resume.cpp
	@echo compiling.release example/test_download_resume.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_download_resume.cpp.o example/test_download_resume.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_http_put.cpp.o: example/test_http_put.cpp
	@echo compiling.release example/test_http_put.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_http_put.cpp.o example/test_http_put.cpp > build/.build.log 2>&1

build/.objs/example.out/linux/x86_64/release/example/test_http_get.cpp.o: example/test_http_get.cpp
	@echo compiling.release example/test_http_get.cpp
	@mkdir -p build/.objs/example.out/linux/x86_64/release/example
	@$(CXX) -c $(example.out_CXXFLAGS) -o build/.objs/example.out/linux/x86_64/release/example/test_http_get.cpp.o example/test_http_get.cpp > build/.build.log 2>&1

clean:  clean_iclient clean_example.out

clean_iclient: 
	@rm -rf lib/linux/libiclient.a
	@rm -rf lib/linux/iclient.sym
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/request.cpp.o
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/response.cpp.o
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/executor.cpp.o
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/http.cpp.o
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/url.cpp.o
	@rm -rf build/.objs/iclient/linux/x86_64/release/src/util.cpp.o

clean_example.out:  clean_iclient
	@rm -rf bin/example.out
	@rm -rf bin/example.out.sym
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_url.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_download_range.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_http_post.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_download_speed_limit.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_download.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/main.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_download_resume.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_http_put.cpp.o
	@rm -rf build/.objs/example.out/linux/x86_64/release/example/test_http_get.cpp.o

