# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

CCACHE=/usr/bin/ccache
MXX=/usr/local/bin/gcc
CXX=/usr/local/bin/gcc
CC=/usr/local/bin/gcc
AS=/usr/local/bin/gcc
MM=/usr/local/bin/gcc

SH=/usr/local/bin/g++
LD=/usr/local/bin/g++
AR=/usr/bin/ar

iclient_CXXFLAGS=-std=c++11 -I/usr/local/include -I/usr/include -m64
iclient_LDFLAGS=-L/usr/local/lib -L/usr/lib -lpthread -lcurl -m64

default:  iclient

all:  iclient

.PHONY: default all  iclient

iclient: bin/iclient
bin/iclient: build/objs/iclient/linux/x86_64/release/iclient/ic_url.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_http.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_executor.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_response.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_util.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_request.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_speed_limit.cpp.o build/objs/iclient/linux/x86_64/release/example/test_url.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_put.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_post.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_resume.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_range.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download.cpp.o build/objs/iclient/linux/x86_64/release/example/main.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_get.cpp.o
	@echo linking.release iclient
	@mkdir -p bin
	@$(LD) -o bin/iclient build/objs/iclient/linux/x86_64/release/iclient/ic_url.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_http.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_executor.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_response.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_util.cpp.o build/objs/iclient/linux/x86_64/release/iclient/ic_request.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_speed_limit.cpp.o build/objs/iclient/linux/x86_64/release/example/test_url.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_put.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_post.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_resume.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download_range.cpp.o build/objs/iclient/linux/x86_64/release/example/test_download.cpp.o build/objs/iclient/linux/x86_64/release/example/main.cpp.o build/objs/iclient/linux/x86_64/release/example/test_http_get.cpp.o $(iclient_LDFLAGS) > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_url.cpp.o: iclient/ic_url.cpp
	@echo ccache compiling.release iclient/ic_url.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_url.cpp.o iclient/ic_url.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_http.cpp.o: iclient/ic_http.cpp
	@echo ccache compiling.release iclient/ic_http.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_http.cpp.o iclient/ic_http.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_executor.cpp.o: iclient/ic_executor.cpp
	@echo ccache compiling.release iclient/ic_executor.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_executor.cpp.o iclient/ic_executor.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_response.cpp.o: iclient/ic_response.cpp
	@echo ccache compiling.release iclient/ic_response.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_response.cpp.o iclient/ic_response.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_util.cpp.o: iclient/ic_util.cpp
	@echo ccache compiling.release iclient/ic_util.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_util.cpp.o iclient/ic_util.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/iclient/ic_request.cpp.o: iclient/ic_request.cpp
	@echo ccache compiling.release iclient/ic_request.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/iclient
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/iclient/ic_request.cpp.o iclient/ic_request.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_download_speed_limit.cpp.o: example/test_download_speed_limit.cpp
	@echo ccache compiling.release example/test_download_speed_limit.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_download_speed_limit.cpp.o example/test_download_speed_limit.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_url.cpp.o: example/test_url.cpp
	@echo ccache compiling.release example/test_url.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_url.cpp.o example/test_url.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_http_put.cpp.o: example/test_http_put.cpp
	@echo ccache compiling.release example/test_http_put.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_http_put.cpp.o example/test_http_put.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_http_post.cpp.o: example/test_http_post.cpp
	@echo ccache compiling.release example/test_http_post.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_http_post.cpp.o example/test_http_post.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_download_resume.cpp.o: example/test_download_resume.cpp
	@echo ccache compiling.release example/test_download_resume.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_download_resume.cpp.o example/test_download_resume.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_download_range.cpp.o: example/test_download_range.cpp
	@echo ccache compiling.release example/test_download_range.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_download_range.cpp.o example/test_download_range.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_download.cpp.o: example/test_download.cpp
	@echo ccache compiling.release example/test_download.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_download.cpp.o example/test_download.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/main.cpp.o: example/main.cpp
	@echo ccache compiling.release example/main.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/main.cpp.o example/main.cpp > build/.build.log 2>&1

build/objs/iclient/linux/x86_64/release/example/test_http_get.cpp.o: example/test_http_get.cpp
	@echo ccache compiling.release example/test_http_get.cpp
	@mkdir -p build/objs/iclient/linux/x86_64/release/example
	@$(CCACHE) $(CXX) -c $(iclient_CXXFLAGS) -o build/objs/iclient/linux/x86_64/release/example/test_http_get.cpp.o example/test_http_get.cpp > build/.build.log 2>&1

clean:  clean_iclient

clean_iclient: 
	@rm -rf bin/iclient
	@rm -rf bin/iclient.sym
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_url.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_http.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_executor.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_response.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_util.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/iclient/ic_request.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_download_speed_limit.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_url.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_http_put.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_http_post.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_download_resume.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_download_range.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_download.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/main.cpp.o
	@rm -rf build/objs/iclient/linux/x86_64/release/example/test_http_get.cpp.o

