target("iclient")
    set_kind("binary")
    set_languages("c99", "cxx11")
    add_files("iclient/*.cpp")
    add_files("example/*.cpp")
    add_links("pthread", "curl")
    set_targetdir("bin")
    set_objectdir("build/objs")
    add_mflags("-O2")
